### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by fantasy1022** [kikoso/eventbus-sample#1]
Hi, 
    It is nice article to introduce EventBus library. But I try this demo APP. It cause RuntimeException in FirstFragment. The message show "de.greenrobot.event.EventBusException: Subscriber class com.enrique.eventbussample.fragments.FirstFragment has no methods called onEvent". So I add onEvent method to FirstFragment, and it can fix this problem. Does every activity or fragment calls onEvent method after it registers EventBus?

**Comment by kikoso** [comment]
Hello @fantasy1022 ,

Somehow I removed the OnEvent method, now is fixed. Every subscriber needs to have at least a method onEvent.
